### ISSUE TITLE
🐛 Bug: Notebook conversion in workflow

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#896] opened 2023-12-01 12:42 UTC
### Describe the bug.

Automated workflows are failing due to an issue in the Colab Notebook workflow: https://github.com/ersilia-os/ersilia/actions/runs/7048990424/job/19186425834

@megamanics : Do you know what may be happening here? Thanks!

### Operating environment

GitHub Actions Ubuntu

**Comment by miquelduranfrigola** [comment] 2023-12-15 20:13
This is useful, thanks! @GemmaTuron do we still need levenshtein? Perhaps we have it as optional?

**Comment by miquelduranfrigola** [comment] 2023-12-19 08:44
I have removed the `levenshtein` dependency (it was not really necessary) but unfortunately this did not solve the issue.
I have decided to remove the workflow step related to the notebook working with Python API. It is somewhat redundant with the CLI step. I am unsure what was going on, in my opinion, it is related to the notebook conversion command.

**Comment by GemmaTuron** [comment] 2023-12-19 08:47
Hi @miquelduranfrigola 

I don't understand, the point of this action was to test the Python API command, the CLI was just an addition, so if anything the CLI is what should be removed.

**Comment by GemmaTuron** [comment] 2023-12-19 09:54
I don't think the issue is with the conversion command, since this works fine for the notebook run with the CLI commands.
The issue is quite simple: we need to install pandas so that the output can be parsed

```
try:
    import pandas as pd
except ModuleNotFoundError:
    pd = None
```

```
File ~/miniconda3/envs/ersilia/lib/python3.10/site-packages/ersilia/core/model.py:212, in ErsiliaModel._api_runner_return(self, api, input, output, batch_size)
    210 def _api_runner_return(self, api, input, output, batch_size):
    211     if output == "pandas" and pd is None:
--> 212         raise Exception
    213     if output == "json":
    214         R = []

```

**Comment by GemmaTuron** [comment] 2023-12-19 10:30
I've tried simply by adding pandas to the installs, it works in my local but for some reason it does not in the workflow file?
https://github.com/ersilia-os/ersilia/actions/runs/7260232462/workflow

**Comment by miquelduranfrigola** [comment] 2024-01-02 15:34
Yes, I do not manage to solve this issue either, @GemmaTuron . For now, I have commented out the API

**Comment by miquelduranfrigola** [comment] 2024-01-03 21:39
Hi @GemmaTuron - I am apparently unable to solve this issue. Should we seek help?

**Comment by GemmaTuron** [comment] 2024-01-04 06:43
@miquelduranfrigola please see my comments regarding pandas in #928 
If we make it a requirement of Ersilia I think the problem will be solved.

**Comment by miquelduranfrigola** [comment] 2024-01-04 07:09
I am ok with having pandas as a dependency.

**Comment by GemmaTuron** [comment] 2024-09-18 14:46
Hi @miquelduranfrigola 

I think this is quite old and not happening any more, but not sure. Pandas is definitely no longer a requirement. @DhanshreeA have you observed this problem or we can close the issue?

**Comment by miquelduranfrigola** [comment] 2024-09-19 22:37
Yes this is quite old indeed. I don't think we use pandas, but @DhanshreeA can confirm

**Comment by DhanshreeA** [comment] 2024-09-22 14:51
Agree with both of you. Pandas is no longer a requirement, and this workflow no longer fails (even if it is not the best representation of what we want - but we can tackle that later). I am closing this issue for now.

**Closed by DhanshreeA** 2024-09-22 14:51 UTC
Labels: bug, help wanted, critical
