### ISSUE TITLE
🐛 Bug: eos526j needs an output adapter to convert json to csv

### ISSUE THREAD

**Issue by ZakiaYahya** [ersilia-os/ersilia#377] opened 2022-10-18 03:14 UTC
### Describe the bug.

@GemmaTuron, I have encountered a endless loop of execution while running predict api on model "eos526j". The model is showing this same behaviour both in google colab and CLI. So for checking purpose i have run the predict api on eos526j for just first one molecule of [test.csv](https://github.com/ersilia-os/ersilia/files/9806127/test.csv). I have encountered error "TypeError: 'NoneType' object is not subscriptable" when i tries to save the predictions in the output.csv file. Here's the screenshot of an error
![eos526j_log1](https://user-images.githubusercontent.com/54974236/196323932-e679cd03-2d17-4d8b-b4b2-b596d4702f7c.png)

I first thought model is not producing output even testing on just one molecule. But when i further dive into it, i get to know that it produces the output but in something different format and when tries to save that predictions in output csv file, it throws an error "TypeError: 'NoneType' object is not subscriptable".

For comparison purpose, i'm attaching the screenshot of prediction results for just one molecule using model eos2v11:
![mine1](https://user-images.githubusercontent.com/54974236/196324717-2342b6a7-20ae-4c5d-9dd6-5d68d4d874f1.png)

Prediction result for just one molecule using model eos526j (CLI): (the full output is not showing in one screenshot that's why i'm attaching log files here):
[CLI.txt](https://github.com/ersilia-os/ersilia/files/9806085/CLI.txt)

Prediction result for just one molecule using model eos526j (Google Colab):
[Colab.txt](https://github.com/ersilia-os/ersilia/files/9806089/Colab.txt)

@GemmaTuron can you please see these outputs? is it correct?. Because other models (i'd run) give output differently ( numeric values)

### Describe the steps to reproduce the behavior

Fetch and run Predict api on model "eos526j" using first one molecule of test.csv file i.e. "Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1"

### Operating environment

Window 10 pro , WLS ubuntu 18.04

### Additional context

Both CLI and Google Colab took  nearly "3 mins and 30 sec" to predict  just one molecule of file. I think this is the reason that it took so much time while predict for whole test.csv file and it seems like it stuck in a endless loop of execution.

**Comment by GemmaTuron** [comment] 2022-10-18 07:43
Hi @ZakiaYahya !

You are right about the model, you can use the [model hub website](https://ersilia.io/model-hub) and search this model using the eos identifier.
You will see it is a tool to calculate "how easy it is to synthesize a molecule in the lab" -- the input molecule is broken down into different precursors (you can imagine it as a Lego) and it gives the precursors you could use to build the molecule (the different lego pieces).

The issue here is how we convert the output (which is a .json format, as you can see printed in the CLI) into a readable pandas object. We need to work on the output adapters for that.
The whole output for a single molecule is this complex json hierarchy:
{
    "input": {
        "key": "MCGSCOLBFJQGHM-SCZZXKLOSA-N",
        "input": "Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1",
        "text": "Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1"
    },
    "output": {
        "type": "mol",
        "smiles": "Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1",
        "children": [
            {
                "type": "reaction",
                "smiles": "[c:1](:[NH:2])([c:3](:[NH:4])[c:5](:[NH:6]):[NH:7])[N:9][CH3:8]>>Cl[c:1](:[NH:2])[c:3](:[NH:4])[c:5](:[NH:6]):[NH:7].[CH3:8][N:9]",
                "children": [
                    {
                        "type": "mol",
                        "smiles": "NC1CC1"
                    },
                    {
                        "type": "mol",
                        "smiles": "Nc1nc(Cl)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1",
                        "children": [
                            {
                                "type": "reaction",
                                "smiles": "[Cl:1][c:2]1[n:3][cH:4]:[N:5]:[c:6](:[NH:7])[c:8]1:[NH:9]>>O=P(Cl)(Cl)[Cl:1].O=[c:2]1[n:3][cH:4]:[N:5]:[c:6](:[NH:7])[c:8]1:[NH:9]",
                                "children": [
                                    {
                                        "type": "mol",
                                        "smiles": "O=P(Cl)(Cl)Cl"
                                    },
                                    {
                                        "type": "mol",
                                        "smiles": "Nc1nc2c(ncn2[C@H]2C=C[C@@H](CO)C2)c(=O)[nH]1"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }
}


You can mark this model as checked in the excel @ZakiaYahya, this is quite complex to tackle now and we will work on it after the contribution period. I am tagging @miquelduranfrigola here to remember this issue.
I hope at least the issue is clear, feel free to ask more questions about it! The model is complex so 3-4 min per molecule could be normal timings.

**Comment by GemmaTuron** [comment] 2022-10-18 07:44
Don't close the issue, but if you can change the title to
"eos526j needs an output adapter to convert json to csv" it will be more informative for us!

**Comment by ZakiaYahya** [comment] 2022-10-18 08:09
> Don't close the issue, but if you can change the title to "eos526j needs an output adapter to convert json to csv" it will be more informative for us!

Sure @GemmaTuron, i have changed the title. Thanks.

**Comment by miquelduranfrigola** [comment] 2022-11-21 19:20
@GemmaTuron what is the current status of this? Converting "any" output to CSV may be difficult at times, so I am not sure we will be able to have this functionality for all models. JSONL format can offer a solution but I haven't given it much thought.

**Comment by carcablop** [comment] 2023-02-07 23:19
Moving this discussion to #560

**Closed** 2023-02-08 07:05 UTC
Labels: bug, help wanted, model-bug
