### ISSUE TITLE
🐛 Bug: eos2r5a predict did not produce an output

### ISSUE THREAD

**Issue by mamabear25** [ersilia-os/ersilia#341] opened 2022-10-14 18:40 UTC
#### Error message:
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

#### more error messages
Something went wrong with Ersilia...
EmptyOutputError

Error message:
Model API eos2r5a:predict did not produce an output

### Describe the steps to reproduce the behavior

1) ersilia fetch -v eos2r5a

### Expected behavior.

fetch model succesfully

### Screenshots.

<img width="1440" alt="Screenshot 2022-10-14 at 19 38 31" src="https://user-images.githubusercontent.com/102018576/195917697-5f0a6270-45f7-4a4d-83d6-dfcb7c88be46.png">
<img width="1440" alt="Screenshot 2022-10-14 at 19 38 39" src="https://user-images.githubusercontent.com/102018576/195917736-c502f96a-0755-4c7c-82a5-dc7a9271d51b.png">

### Operating environment

macOs Monterey Version 12.5.1

**Comment by Zainab-ik** [comment] 2022-10-15 05:58
@mamabear25 kindly add your log file for easy debugging.

**Comment by GemmaTuron** [comment] 2022-10-16 13:26
Hi @mamabear25 as Zainab just pointed out I would need to see the full log error file for helping you

Thanks!

**Comment by mamabear25** [comment] 2022-10-16 13:35
Here's my log
[my.log](https://github.com/ersilia-os/ersilia/files/9794669/my.log)

**Comment by GemmaTuron** [comment] 2022-10-16 13:41
Hi @mamabear25 

It seems that the issue is on git - lfs:

`git: 'lfs' is not a git command. See 'git --help'.`

Make sure it is installed and recognized, sometimes after git lfs install you need to restart the system.

**Comment by Chigoziee** [comment] 2022-10-16 17:09
this was helpful reinstalling git - lfs worked

**Comment by Chigoziee** [comment] 2022-10-16 17:10
This was helpful, installing git - lfs solved the issue.

**Comment by mamabear25** [comment] 2022-10-17 09:54
I installed git-lfs but I'm still having the same issue.
Should i install it in ersilia environment? @Chigoziee

**Comment by mamabear25** [comment] 2022-10-17 09:56
I installed git-lfs but I'm still having the same issue.
did you install it with pip or conda? @Chigoziee

**Comment by GemmaTuron** [comment] 2022-10-17 10:17
I'd suggest conda-forge, and re-start the whole system.
Then check if it is recoginsed inside the ersilia conda environment

`conda install git-lfs -c conda-forge`
`git-lfs install`

**Comment by mamabear25** [comment] 2022-10-17 10:22
On it!!!

**Comment by mamabear25** [comment] 2022-10-17 10:51
still doesn’t work, 
I've fetched other models successfully and even tried models assigned to other people and it was successful.

**Comment by mamabear25** [comment] 2022-10-17 12:28
I was using the command pip install git-lfs instead of `git-lfs install` to initialize  Git LFS

### Solution:
1. installed xgboost again (Not sure if it had any effect)

2. conda install git-lfs -c conda-forge
3. git-lfs install
4. ersilia -v fetch eos2r5a

### response:
👍 Model eos2r5a fetched successfully!

Thanks so much @GemmaTuron

**Comment by GemmaTuron** [comment] 2022-10-17 12:49
yay there we go! 

Im closing this issue then!

**Closed by GemmaTuron** 2022-10-17 12:49 UTC
Labels: bug, dependencies-issue
