### ISSUE TITLE
🐛 Bug: Model eos4b8j and eos7jlv - Google Colab - Output adaptors needed

### ISSUE THREAD

**Issue by thormiwa** [ersilia-os/ersilia#384] opened 2022-10-19 03:13 UTC
### Describe the bug.

Both models have an API: PREDICT with each of them giving a `ValueError: Columns must be same length as key` everytime you predict. 
Link to each model google colab 
[eos4b8j](https://colab.research.google.com/drive/1_3jZ7jzheZmfSebaiOmQnEzeR9Q3zZ2M?usp=sharing)
[eos7jlv](https://colab.research.google.com/drive/1QEp7-vMulA1DeDdFZ3U7IjreNch51Du9?usp=sharing)

### Describe the steps to reproduce the behavior

Fails after running [this command](https://colab.research.google.com/drive/1QEp7-vMulA1DeDdFZ3U7IjreNch51Du9#scrollTo=pk6y_qQcXTPR&line=5&uniqifier=1) for like 20 mins so i am convinced it is almost at the end of the prediction it happens.

### Operating environment

Colab

**Comment by GemmaTuron** [comment] 2022-10-19 15:55
Hi  @thormiwa !

Can you check what happens if you only pass one molecule for prediction?
instead of input=smiles, write input="CCCC"

**Comment by thormiwa** [comment] 2022-10-19 16:08
Hi @GemmaTuron  i get this error when i do that ` PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance. `

[eos4b8j](https://colab.research.google.com/drive/1_3jZ7jzheZmfSebaiOmQnEzeR9Q3zZ2M?usp=sharing)
[eos7jlv](https://colab.research.google.com/drive/1QEp7-vMulA1DeDdFZ3U7IjreNch51Du9?usp=sharing)

**Comment by GemmaTuron** [comment] 2022-10-19 17:01
Thanks @thormiwa !
This is due to the input-output format which we are trying to constrain to a pandas dataframe.
Just last check, to help us improve on this error.
Can you run, from Google Colab, using CLI commands and see what output you get?

After fetching, do:
`!ersilia serve 4b8j`
`!ersilia -v api predict -i "CCCCC"`

The ! indicates a CLI command to run on a jupyter notebook

**Comment by thormiwa** [comment] 2022-10-19 17:08
@GemmaTuron Using CLI commands worked for both models. :)

**Comment by GemmaTuron** [comment] 2022-10-20 12:27
Cool so we need to work on the input/output adaptors.
Im gonna flag this for future work, can you change the title to:
**eos4b8j and eos7jlv - Google Colab - Output adaptors needed**

**Comment by pauline-banye** [comment] 2022-12-19 18:35
#Issue
These models are predicted successfully on the CLI but fail on google colab
![colab err](https://user-images.githubusercontent.com/63536707/208482934-6abb22f7-7543-4f1b-b407-c36da05c2a6a.png)

#Observation 
I tried to do some research as to why it was returning this error and  the underlying problem is caused by the shape of the object. The  dimension must match the number of columns you're trying to assign to.

I had a look at the model csv output from the CLI and noticed they each had 100 smi columns. I haven't observed this on any of the other models and I compared it to eos9ei3 which fetched successfully on both colab and the CLI.
output of eos9ei3
[eos9ei3.csv](https://github.com/ersilia-os/ersilia/files/10261549/eos9ei3.csv)

Output of eos7jlv and eos4b8j on the CLI
[eos7jlv-CLI.csv](https://github.com/ersilia-os/ersilia/files/10261330/eos7jlv.csv)
[eos4b8j-CLI.csv](https://github.com/ersilia-os/ersilia/files/10261346/eos4b8j.csv)

**Comment by AdedejiAdewole** [comment] 2023-03-28 06:36
Hello @GemmaTuron. I have looked into this issue you assigned to me and I think I know the problem here. It's how the outputs are stored. So in the model.py file, there are three options to save outputs which are "numpy", "pandas" and "dict" corresponding to lists, dataframes and dictionaries respectively. I realised the problem was in how the outputs are saved as dataframe which is the "pandas" option that is selected by default in the Ersilia notebooks. The code to select "pandas" as an option is below:

`output = model.api(input=smiles, output="pandas")`

Now an error comes up right at the moment where the outputs are supposed to be saved so I traced it to the model.py file in the site-packages repo and saw this:

```
if output == "numpy":
    return data.values[:]
if output == "pandas":
    d = collections.OrderedDict()
    d["key"] = data.keys
    d["input"] = data.inputs
    df = pd.DataFrame(d)
    df[data.features] = data.values
    return df
if output == "dict":
     d = collections.OrderedDict()
     d["keys"] = data.keys
     d["inputs"] = data.inputs
     d["values"] = data.values
     return d
```

The error is as a result of this line of code "df[data.features] = data.values", right after the Dictionary has been converted to a DataFrame. It tries to assign keys to each output in the similarities columns and it runs out of keys to assign. I mean even in the first output that contains 100 similarities, it tries to assign a key to each of those 100 similarities instead of treating the 100 similarities as one output.

I saved a copy of the notebook and tweaked the code to this and it solved the error. This makes the 100 similarities of each column to be treated as a single output and assigns the corresponding keys to the outputs.

```
if output == "numpy":
    return data.values[:]
if output == "pandas":
    d = collections.OrderedDict()
    d["key"] = data.keys
    d["input"] = data.inputs
    d["values"] = data.values
    df = pd.DataFrame(d)
    return df
if output == "dict":
     d = collections.OrderedDict()
     d["keys"] = data.keys
     d["inputs"] = data.inputs
     d["values"] = data.values
     return d
```

The output of the prediction is provided below:
[eos4b8j_output.csv](https://github.com/ersilia-os/ersilia/files/11086055/eos4b8j_output.csv)

My Ersilia notebook
[copy of my ersilia notebook](https://colab.research.google.com/drive/1jkkJaPfHUEd3PcrNMirPZasDJH07o0OG#scrollTo=1cg9EqzVnJSs)

I hope this solves this issue :)

**Comment by GemmaTuron** [comment] 2023-03-28 12:36
Hi @AdedejiAdewole !

Fantastic job! I cannot access the notebook but the explanation is detailed enough.
Can you share a link to the `model.py` file where the function that should be modified is?

**Comment by AdedejiAdewole** [comment] 2023-03-28 15:23
Okay @GemmaTuron .
This is the link to the file.
https://github.com/ersilia-os/ersilia/blob/master/ersilia/core/model.py

**Comment by AdedejiAdewole** [comment] 2023-03-29 10:14
Okay true that. I'm here to help :) @GemmaTuron

**Comment by GemmaTuron** [comment] 2023-08-10 17:49
these models now output a list in .csv format, so they work fine in colab

**Closed by GemmaTuron** 2023-08-10 17:49 UTC
Labels: bug, help wanted, model-bug
