### ISSUE TITLE
🐛 Bug: Fetching model eos1af5 with "EmptyOutputError"

### ISSUE THREAD

**Issue by 0xxhaisenberg** [ersilia-os/ersilia#443] opened 2022-10-25 10:23 UTC
### Describe the bug.

raise EmptyOutputError(model_id=self.model_id, api_name=api_name)
ersilia.utils.exceptions_utils.exceptions.EmptyOutputError: Ersilia exception class:
EmptyOutputError

Detailed error:
Model API eos1af5:predict did not produce an output
[eos1af5.log](https://github.com/ersilia-os/ersilia/files/9859191/eos1af5.log)

### Describe the steps to reproduce the behavior

ersilia -v fetch eos1af5 >> eos1af5.log 2>&1

### Expected behavior.

Model eos1af5 fetched successfully

### Screenshots.

![Screenshot from 2022-10-25 10-59-07](https://user-images.githubusercontent.com/41090568/197744196-76e6a681-96a8-4ec5-b3d6-37dc677ee4b6.png)

### Operating environment

Ubuntu 20.04.3 LTS

### Additional context

Model worked smoothly on colab.

I tried to fetch another model but got the same error

I re-fetched the dummy model eos3b5e and it ran successfully

**Comment by GemmaTuron** [comment] 2022-10-25 14:48
Hello @0xxhaisenberg 

make sure you have updated the pip and conda packages. as you can see, some packages can't be fetched which is the source of your errors. Activate the eos1af5 conda env and let me know if the packages mentioned in your error are installed or not
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dgllife 0.2.3 requires hyperopt, which is not installed.
```

**Comment by 0xxhaisenberg** [comment] 2022-10-26 13:23
Updating conda packages and pip did not resolve the issue

checking the list of installed packages in the eos1af5 environment shows thus:
[eos1af_installed_packages.log](https://github.com/ersilia-os/ersilia/files/9869806/eos1af_installed_packages.log)

**Comment by GemmaTuron** [comment] 2022-11-21 19:33
This model has been tested in a windows and unix system and it worked, the issue is dependant on the contributor's set up system. I'll close this issue if no one else is experiencing problems with it

**Closed by GemmaTuron** 2022-11-21 19:33 UTC
Labels: bug
