### ISSUE TITLE
✍️ Contribution period: Joyesh Banerjee 

### ISSUE THREAD

**Issue by joiboi08** [ersilia-os/ersilia#832] opened 2023-10-04 09:35 UTC
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [x] Install the model in your system
- [x] Run predictions for the EML
- [x] Compare results with the Ersilia Model Hub implementation!
- [x] Install and run Docker!

### Week 3 - Propose new models

- [x] Suggest a new model and document it (1)
- [x] Suggest a new model and document it (2)
- [x] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [x] Submit the final application in the Outreachy website

**Comment by joiboi08** [comment] 2023-10-05 11:59
### WEEK 1 - Updates ###
Task 1 - I joined Esilia's Slack channel from their Outreachy landing page and was welcomed by a community of warm peers and team leads! It was reassuring and exciting to be part of something like this.

Task 2 - Opened this issue with success! :) 

Task 3 - 
Since I am using a Windows platform, I installed WSL and Ubuntu terminal environment as [mentioned here.](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation)
Faced a small issue in my Ubuntu terminal not recognising WSL so I had to manually enable it from Windows Features. It worked fine afterwards. Continued through the mentioned steps.

I installed all prerequisites - 

- gcc compiler
- installed and updated Conda to latest release `23.9.0` 
- I already had Python version `3.11.4`

But during installation of Github CLI and Github authentication, I faced an issue where terminal did NOT return after `Login with Web Browser` was chosen. It says 'Press Enter to go to Github.com' and gives an error saying I don't have the dependencies in the $PATH variable. The main problem lies after this : 
It says 'Please try entering the URL in your browser manually' but it never returns after this. 
Any help here is appreciated @carcablop

**Comment by joiboi08** [comment] 2023-10-05 14:38
### Task 3 ###

So I am facing issues in calling `ersilia catalog` where it mentions a Errno:101 Network Unreachable error. I have attached a log file below.
[myfile.log](https://github.com/ersilia-os/ersilia/files/12819605/myfile.log)
`ersilia --help` works fine. 
So I moved on to `ersilia -v fetch eos3b5e` which is also not working with a different error (log file below)
[fetchLog.log](https://github.com/ersilia-os/ersilia/files/12819638/fetchLog.log)

**Comment by joiboi08** [comment] 2023-10-05 15:07
I have found a solution to this issue. Certain service providers block githubraw and that was causing the Errno101. People may try switching to a different service provider but a more feasible solution is changing your DNS to -
Cloudfare DNS 
`1.1.1.1 
1.0.0.1`  for ipv4
and 
`2606:4700:4700::1111
2606:4700:4700::1001` for ipv6. 


This has worked well for me and I have successfully tested and used a simple model deployment of Ersilia, getting the desired result that was [specified in the instructions.](https://ersilia.gitbook.io/ersilia-book/contributors/internships/outreachy-winter-2023)

This was a great learning experience for me as this is my first time and I'm excited for what is to come next! 
I now mark task 3 as completed.

**Comment by joiboi08** [comment] 2023-10-05 23:28
## Motivation Statement   - Task 4 ##

My name is Joyesh Banerjee. I am an engineering graduate from India and did it in electronics and communication engineering. I started out with C and Java but shifted to Python after a while because I was garnering interest in data analysis and later data science in general. I did a few college projects in which we trained a prediction model based on open source datasets and I found the work lively and rewarding. I come from a lower middle class family and have always lived by the skin of our teeth but all thanks to God, we have come far. Every parent works through their bones to give their children a better platform to grab opportunities than they had and I believe this is such a platform that they envisioned for us. 
 
I came across Outreachy as a recommendation from a friend who applied previously and I was warmed by how much soul they had as an organization. They were incredibly inclusive and gave me a chance to really tell my story in my application which I appreciated, so did many of my peers I am sure of it. So I was very happy I was given a chance as a contributor here, because when I was going through the projects - I felt a similar blow of warmth from Ersilia. This was corroborated by the cordial and supportive team I found myself in when I joined their channels. They were prompt and provided quick resolutions for issues. The best part was - even when many of us were facing issues in some initial tasks, in the time the solution had not been found the team was interactive and didn't keep us in the dark.
I already have some experience with training models so I firmly believe my time in the internship will be the perfect incubator for my skills to grow rapidly and showcase themselves in the best of ways - helping people in need. 
And for that I am primed and ready to learn and apply myself to the fullest. After the internship period has ended, I intend to keep applying my competence here by working with the community to plan meaningful contributions. I also want to challenge myself by learning new tech stacks like cloud (AWS) to make deployment of these models more efficient for users and further supplement Ersilia's growth. I want to eventually learn new skills to find a way to enhance current processes. 

I have also seen my fair share of medical issues and what hurts most is medical incompetence. I lost my grandmother to undiscovered side effects during her treatment which blindsided the family and the doctors on her case. When I went through Ersilia's objectives and intentions with this technology, I couldn't help but think what could have happened if someone had thought of this a decade earlier. 

As the saying goes - "The best time to plant a tree was 10 years ago. The second best time is now."


This community is working on a novel goal that will help countless people and I wish to become part of that effort to my utmost. It will swell my heart with joy if I can help further this idea to reality - so that a decade from now maybe one less child will wish **someone had thought of something today.**

**Comment by joiboi08** [comment] 2023-10-06 00:15
## Submit your first contribution to Outreachy - Task 5 ##

After providing a detailed motivational letter, I have submitted a contribution report through Outreachy and linked this issue as instructed! The contribution has been recorded successfully.  
### **This marks the end of all Week - 1 tasks and is hence brought to a closure.** ###

**Comment by DhanshreeA** [comment] 2023-10-06 11:48
Hello @joiboi08 thank you for the detailed updates. If you'd like, you can get started with the tasks from week 2 now. :)

**Comment by joiboi08** [comment] 2023-10-06 12:11
> Hello @joiboi08 thank you for the detailed updates. If you'd like, you can get started with the tasks from week 2 now. :) 

Thank you! I'll update my progress in week 2 shortly.

**Comment by joiboi08** [comment] 2023-10-07 14:15
# Week - 2 #
After completing week - 1 tasks, attending a wonderful and informative session and some personal time - I have begun work on **week 2!**

Tasks of this week pit us the closest to real-internship work so far. Understood summary of tasks - 

- install one of the [suggested models](https://ersilia.gitbook.io/ersilia-book/contributors/internships/outreachy-winter-2023) and run them locally, reference the author's repo and source code as needed. Mention why this mode was chosen.
- once installed and successfully tested, use the [Essential Medicines List](https://raw.githubusercontent.com/ersilia-os/ersilia/master/notebooks/eml_canonical.csv) CSV as in input for the chosen model. Use third party implementation of the model to extract output.

- compare this output to the Ersilia Model Hub implementation of the same model. Note any differences or points of interest. Since I have no experience with Docker, I will test myself and use a Docker container to implement the Ersilia Model.

This is my interpretation of the Week - 2 tasks. If I misinterpreted something I am happy to be corrected.


## Task 1 - Choose a model, explain why and run it locally ##

For this task, I was **divided** between **PPBopt model** and the **STOUT model**.  My understanding of the former is that it is a prediction engine that predicts how well a compound binds with blood for transportation to target sites, finding important use cases in optimizing drug development costs and time. This model was interesting and is also the closest to my experience as I have worked on prediction models before.


However, 
I wanted to try something different and the STOUT model peaked my interest. My understanding of it is converts a compound's SMILE name (which is essentially the **ASCII-symbol representation of its structure** so it is machine readable) to its IUPAC defined name and vice-versa. An exciting thing was it used TensorFlow!! I have never worked with TensorFlow before (only Sklearn) so this was a nice challenge for myself to grab a cup of coffee and learn a new library!

**Hence, I opted to work with the STOUT model.**

**Comment by joiboi08** [comment] 2023-10-07 15:19
## Task 2 - Install and run the STOUT model locally ##

To start with, I am following [these steps](https://github.com/Kohulan/Smiles-TO-iUpac-Translator) for the STOUT model installation.

First, I open my local Linux environment that I setup in the [Week - 1 tasks.](https://github.com/ersilia-os/ersilia/issues/832#issuecomment-1748742037) I run some `-- version` checks to ensure I am using appropriate versions - 
Python `3.11.4`
Conda `23.9.0` and WSL `2`

**All good!** Onto the installation!

- I first create a conda environment to activate the model in :
 `conda create --name STOUT` 


- Activating STOUT 
`conda activate STOUT`


- Installing dependencies 
`conda install -c decimer stout-pypi`

Two tries were made to fetch repo data but failed. 
Log file for the failure - [fail.log](https://github.com/ersilia-os/ersilia/files/12838095/fail.log)
It could not find the `pystow` package.

So I tried using alternate methods mentioned in the repo - 
`pip install STOUT-pypi`
It successfully installed all required packages! (worth ~624MB!)

Since the model was now installed, I was ready to test!

**Comment by joiboi08** [comment] 2023-10-07 16:03
While testing, I am running into some issues.

I needed a dataset for testing and I found a [demo dataset](https://github.com/Kohulan/Smiles-TO-iUpac-Translator/blob/main/STOUT/predictor_demo.py) in the STOUT repo and tried to use it. However, it keeps giving me a ImportError - log attached below.
[logs.log](https://github.com/ersilia-os/ersilia/files/12838189/logs.log)

**Comment by joiboi08** [comment] 2023-10-07 17:59
I was primarily running this on Ubuntu but I have since switched to VSCode (and its CLI) for better maneuverability.
I got the same ImportError referenced above. I found a solution by changing the relative import in the [stout.py file](https://github.com/Kohulan/Smiles-TO-iUpac-Translator/blob/main/STOUT/stout.py) to an absolute import : 

`from .repack import helper`  to `from repack import helper`

This allowed me to move forward. After I ran the code again, it finally downloaded the model and gave me success message (in the VSCode CLI) that model was loaded. But when it compiling the code, it tagged the IUPAC_names_test.txt file with a  FileNotFoundError
So I switched the working directory to `cd STOUT` which solved it.

**Comment by joiboi08** [comment] 2023-10-07 19:44
## Task 3 - Running the model with EML as the input dataset ##

Now that we have setup our model and tested it once, we use it in a pseudo-real time scenario. 

- First, we go through the [EML dataset provided here ](https://raw.githubusercontent.com/ersilia-os/ersilia/master/notebooks/eml_canonical.csv) to determine what kind of conversion is being made.
- I can see that three categories are given 
                 - `drugs` or common name 
                 - `smiles`
                 - `can_smiles`

**Comment by joiboi08** [comment] 2023-10-08 17:41
## Task 4 - Docker Deployment of the Ersilia Hub implementaion of the STOUT Model ##

- I want to try completing this using docker!

**Comment by leilayesufu** [comment] 2023-10-09 17:39
Have you tried giving it a single input as opposed to the entire EML file to test it?

**Comment by joiboi08** [comment] 2023-10-09 17:49
Hi @leilayesufu 
I haven't processed the entire file yet. I was feeding it a modified dataset [task3.csv](https://github.com/ersilia-os/ersilia/files/12841673/task3.csv) of 2 inputs as a test before giving it the entire EML set.

**Comment by leilayesufu** [comment] 2023-10-09 17:59
Okay, try testing it with a single input directly as though.
 ersilia -v api run -i "Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1" not through the file

**Comment by joiboi08** [comment] 2023-10-09 18:09
I've run into a worse problem. I am unable to fetch or serve models. I keep getting the `connection reset by peer` error without fail. I have reinstalled the environment multiple times without this changing. 
[ConnectionResetLog.log](https://github.com/ersilia-os/ersilia/files/12849190/ConnectionResetLog.log)

**Comment by leilayesufu** [comment] 2023-10-09 18:16
I'm going to try to do it, and i'll get back to you

**Comment by leilayesufu** [comment] 2023-10-09 19:57
HI, so i fetched the model and served it as seen

<img width="431" alt="fetch and serve" src="https://github.com/ersilia-os/ersilia/assets/78659709/2aad6849-4c0d-4349-bccb-bb394822393a">

then i ran `ersilia card  eos4se9`, the output showed as seen [here](https://github.com/ersilia-os/ersilia/files/12849499/my.log)

> "Code": "$ ersilia serve smiles2iupac\n$ ersilia api -i 'CCCOCCC'\n$ ersilia close",

So to run predictions, i just did  `ersilia api -i "CCCC"` and i got the output below 
[here](https://github.com/ersilia-os/ersilia/files/12849951/mylogs.txt)

This was just a simple texting although @Promisefru ran it with some inputs from the EML file and it gave him a null output

**Comment by joiboi08** [comment] 2023-10-10 14:33
Hi @leilayesufu 
Thank you for trying this out for yourself. 
I reinstalled my environment and tried your steps to-the-letter, but I kept getting one of three errors 
- Errno104 `Connection reset by peer`  
[wood.log](https://github.com/ersilia-os/ersilia/files/12858428/wood.log)

- Errno111 `Max retries/Connection refused ` this happened only once

**Comment by leilayesufu** [comment] 2023-10-10 20:38
HI, I'm thinking it could be your network then

**Comment by joiboi08** [comment] 2023-10-11 10:54
Hi @leilayesufu 
I have a strong connection and I have also made sure I am not running into [this error again](https://github.com/ersilia-os/ersilia/issues/832#issuecomment-1749042746) as I can view githubraw files. I previously was able to fetch and run models but I have only recently been unable to do so.

**Comment by joiboi08** [comment] 2023-10-12 05:34
Thank you @DhanshreeA and @leilayesufu. I am looking forward to the updates.
Meanwhile is it ok if I move on to Week - 3 tasks for now?

**Comment by leilayesufu** [comment] 2023-10-12 07:38
Hi, since the problem is a geographical one. I'll suggest using a vpn and changing your location to complete your week 2 tasks. Ofcourse, you'll need the go ahead from @DhanshreeA

**Comment by joiboi08** [comment] 2023-10-13 15:05
Hi @leilayesufu, thank you for your suggestion. I ran a VPN and did a fresh install of ersilia and the conda environment as well as the git packages. It is now successfully able to fetch and serve models so I am a little relieved. I believe my peer @Ajoke23 also mentioned this on Slack, thank you as well.
@DhanshreeA VPN is working as an interim solution for the regional service outages.

Currently, I am again facing [this problem](https://github.com/ersilia-os/ersilia/issues/832#issuecomment-1752114855) - `TypeError: object of type 'NoneType' has no len()`
I am trying some solutions and will update here.

**Comment by joiboi08** [comment] 2023-10-18 10:03
# Week - 3 #

Marks the start of some real field work!



## First Model Proposition ##
**PIGNet2 - A Versatile Deep Learning-based Protein-Ligand Interaction Prediction Model for Binding Affinity Scoring and Virtual Screening** 



- Publication - [Papers With Code](https://paperswithcode.com/paper/a-versatile-deep-learning-based-protein)

- Source Code - [Github](https://github.com/ace-kaist/pignet2)

- Authors :  Seokhyun Moon, Sang-Yeon Hwang, Jaechang Lim, Woo Youn Kim  

- Date Published - July 3, 2023               





### My interpretation of the model : 
- **Their objective** is to predict PLI (Protein-Ligand Interaction) in the form of screening (identifying compounds that possibly have binding affinity OR do not have it) and scoring (predicting the binding affinity of the protein-ligand complex in a way that is comparable to experimental values) as well as improving the binding process.

**Comment by DhanshreeA** [comment] 2023-10-18 12:45
> Hi @leilayesufu, thank you for your suggestion. I ran a VPN and did a fresh install of ersilia and the conda environment as well as the git packages. It is now successfully able to fetch and serve models so I am a little relieved. I believe my peer @Ajoke23 also mentioned this on Slack, thank you as well. @DhanshreeA VPN is working as an interim solution for the regional service outages.
> 
> Currently, I am again facing [this problem](https://github.com/ersilia-os/ersilia/issues/832#issuecomment-1752114855) - `TypeError: object of type 'NoneType' has no len()` I am trying some solutions and will update here.
> 
> 🟢 🟢 **SOLUTION -** On the advice of my peer @AlphonseBrandon I added headers to my input file and it worked. Thank you so much.
> 
>     * Input file
>       [eml.csv](https://github.com/ersilia-os/ersilia/files/12895576/eml.csv)
>       This file has the first 20 rows of canonical SMILES names (excluding the header row) to match the 20 rows of input used in 3rd party STOUT model implementation.
> 
> 
> Now, I feed the this file into my fetched model `eos4se9` using the command `$ ersilia -v api run -i 'eml.csv' -o 'result.csv'`
> 
>     * Now, I get the result output file
>       [result.csv](https://github.com/ersilia-os/ersilia/files/12895771/result.csv)
> 
> 
> ### BUT
> 
> The first 9 rows do not have a translation. I ran it again and this time I did NOT have any rows translated. During both the processes, two things happened consistently -
> 
>     1. Batch prediction failed and it swtiched to individual prediction
> 
>     2. I got a 504 error from every single row that failed to translate
> 
> 
>     * I always get these DEBUG logs :
> 
> 
> ```
> 11:24:14 | DEBUG    | Starting Docker Daemon service
> 11:24:14 | DEBUG    | Creating temporary folder /tmp/ersilia-nb24uaof and mounting as volume in container
> 11:24:14 | DEBUG    | Image ersiliaos/eos4se9:latest is available locally
> 11:24:14 | DEBUG    | Using port 46089
> ```
> 
>     * I didn't really have experience with Docker, but from what I could tell, the inputs were given to a remote **docker container** running the `eos4se9 model` which in turn returned predictions. And googling the `error 504` informed me it is a timeout error. So basically, I was not getting translated outputs because the container kept getting timed out.
> 
>     * I searched around and found two solutions -
>       1. Instead of communicating with a remote container, I run the predictions directly from within the container.
>       2. Increase the nginx request timeout.
> 
>     * I chose **option 1** as it will allow me to gain more experience with Docker implementation.
> 
>     * So - as I fetch and serve the models on Ubuntu, I see a corresponding container being created on Docker Desktop. From here, I can get my `container ID` to call it in Ubuntu.
>       From Docker Desktop, my current running container has id - `eos4se9_7a24`
> 
>     * Since processing the entire EML dataset will take an impractical amount of time (mainly due to hardware limitations), I have taken the first 20 rows of the dataset as input for both the STOUT 3rd party model and the Ersilia Hub Model.
> 
>     * I already have a modified dataset [er_task3.csv](https://github.com/ersilia-os/ersilia/files/12907831/er_task3.csv) so the step to take here is to copy this file into the working dir of my container.
> 
>     * I was able to complete this step using the docker `cp` command -
> 
> 
> `$ docker cp er_task3.csv eos4se9_7a24:/root`
> 
> Thank you @leilayesufu @PromiseFru for helping me figure out the container dir!
> 
>     * Now the modified dataset er_task3.csv is copied into the working dir of the container.
> 
> 
> To access this container through Ubuntu, I use the command -
> 
> `$ docker exec -it eos4se9_7a24 sh`
> 
>     * Check to see if the dataset is present using
>       `# ls`
>       ![image](https://user-images.githubusercontent.com/94055810/275242982-3aad8167-456f-4d01-b69e-a434d08b3e22.png)
> 
> 
> It is! Great!
> 
>     * We input the dataset here and run the model and output the result into a file
> 
> 
> `# ersilia -v api run -i er_task3.csv -o er_result.csv`
> 
>     * Now, the generated result is still in the container and to access it, we need to copy it to our local system
> 
> 
> `$ docker cp eos4se9_7a24:/root \\wsl.localhost\Ubuntu\home\joyesh\miniconda3\envs\ersilia`
> 
> Here, the container files are copied over to the mentioned destination and we can easily find our result file here.
> 
> [er_result.csv](https://github.com/ersilia-os/ersilia/files/12906298/er_result.csv)
> 
> **Successfully predicted all SMILES names to IUPAC!**
> ## Comparison between STOUT implementation and Ersilia implementation
> 
> After getting both results, I wanted to combine both result files into a single csv or excel file. For that, I wrote some python code to :
> 
>     * turn both .csv files into respective lists
> 
> 
> I used the csv module again
> 
> ```python
> import csv 
> 
> with open("er_result.csv", newline='') as ers :
>     ers_base_list = list(csv.reader(ers))  # list of list of each ersilia translation row
> 
> ers_list = []
> for name in ers_base_list[1:] :
>     ers_list.append(name[2])  # extracting only rows under iupacs_names column
> 
> with open("111predicted_iupac111.csv", newline='') as stout : 
>     stout_base_list = list(csv.reader(stout)) # list of list of stout translation rows
> 
> stout_list = []
> for name in stout_base_list : # no headers in this file
>     stout_list.append(name[0]) # list of stout translations
> ```
> 
>     * combine those lists into **one** list of format :  `[<STOUT iupac name>, <Ersilia iupac name>]`
> 
> 
> ```python
> result_list = []
> for i in range(0,20) :  # because 20 SMILES names were translated
>     result_list.append(stout_list[i]) # adding STOUT IUPAC
>     result_list.append(ers_list[i])   # adding Ersilia IUPAC
> ```
> 
>     * turn that list into a single .csv file
> 
> 
> ```python
> with open("comparison_result.csv", "w") as comp :
>     writer1 = csv.writer(comp)
>     for i in result_list :
>         writer1.writerow([i])    
> ```
> 
>     * The resultant comparison file
>       [comparison_result.csv](https://github.com/ersilia-os/ersilia/files/12907649/comparison_result.csv)
> 
> 
> ### My Interpretations
> 
>     * The STOUT third party model was for me more modular in terms of determining an output format. The output file generated [as seen here](https://github.com/ersilia-os/ersilia/files/12896825/111predicted_iupac111.csv) does NOT have excess columns, only the translated IUPAC names. This made it easier to work with as it required less cleaning/prepping.
> 
>     * The Ersilia Model however gives a verbose multi-column list without an opportunity to change that output since the output file is generated directly by the model. Whereas in the STOUT model, we imported the STOUT module and used the `translate forward` function in the code we write from scratch.
> 
>     * On the flipside, this makes the Ersilia Model implementation more time efficient as no `python` is needed to generate an output file. This has greater weight as deployment time and efficiency is higher here.
> 
>     * As for the result contents itself, there is mostly no difference save for a few situations. The models perform similarly/identically for smaller, less complex inputs like `CCCC` or `CC(=O)O`
> 
>     * But minor differences start to show for larger, more complex inputs as seen here :
> 
> 
> ```
> (3S,8R,9S,10R,13S,14S)-10,13-dimethyl-17-pyridin-3-yl-2,3,4,7,8,9,11,12,14,15-decahydro-1H-cyclopenta[a]phenanthren-3-ol
> 
> (1S,2S,5S,10R,11R,14S)-5,11-dimethyl-5-pyridin-3-yltetracyclo[9.4.0.02,6.010,14]pentadeca-7,16-dien-14-ol
> ```
> 
> This week was the greatest challenge yet as I made myself familiar with new technology and got stuck A LOT!! However, it was joyous to see myself progress. Excited for the next tasks!
> ### Marking Week - 2 complete!

Hi @joiboi08 many congratulations on making it this far. Good job on learning more about working with 
docker, thank you @leilayesufu and @PromiseFru for all the help here. 

As for the network connection we faced earlier, the issue seemed to have resolved on its own after a couple of days, and I can work with Ersilia normally again without VPN. (As guessed, it was probably a geographical outage)

**Comment by joiboi08** [comment] 2023-10-18 13:02
I'm having fun learning new things! @DhanshreeA 
And thank you for the update! It is a relief that it is not something permanent ☺️

**Comment by joiboi08** [comment] 2023-10-19 18:28
## Running The Model

To run this model, I followed the instructions mentioned in their [repository.](https://github.com/ACE-KAIST/PIGNet2)
- This mode is based on pytorch, so I opened Ubuntu and installed pytorch using -

```linux
pip3 install torch torchvision torchaudio
```
`pip3 install torch torchvision torchaudio`

This command was generated by [the pytroch website](https://pytorch.org/get-started/locally/) according to the options you need.

- I cloned the PigNet2 repository 

```linux
gh repo clone ACE-KAIST/PIGNet2
```


- Created a conda environement 

```linux
conda create -n pignet2 python=3.9
conda activate pignet2
```

- Installed the [requirements file ](https://github.com/ACE-KAIST/PIGNet2/blob/main/requirements.txt)

```linux
pip install -r requirements.txt
```

**Comment by joiboi08** [comment] 2023-10-22 11:20
## Second Model Proposition ##
**ChemProp - A Message Passing Neural Network for Molecular Property Prediction and its Application in A Deep Learning Approach to Antibiotic Discovery** 



- Publication - [CELL](https://www.cell.com/cell/fulltext/S0092-8674(20)30102-1#secsectitle0020)

- Source Code - [Github](https://github.com/chemprop/chemprop)

- Authors :  Jonathan M. Stokes, Kevin Yang, Kyle Swanson, Wengong Jin, Andres Cubillos-Ruiz, Nina M. Donghia, Craig R. MacNair, Shawn French, Lindsey A. Carfrae, Zohar Bloom-Ackermann, Victoria M. Tran, Anush Chiappino-Pepe, Ahmed H. Badran, Ian W. Andrews, Emma J. Chory, George M. Church, Eric D. Brown, Tommi S. Jaakkola, Regina Barzilay, James J. Collins  

- Date Published - February 20, 2020               





### My interpretation of the model : 
- **Their objective** 

- **Why?** 

- **Their solution** 


### Relevance to Ersilia 

-

**Comment by joiboi08** [comment] 2023-10-23 11:36
## Third Model Proposition ##
**AMPlify: attentive deep learning model for discovery of novel antimicrobial peptides effective against WHO priority pathogens** 



- Publication - [PubMed](https://pubmed.ncbi.nlm.nih.gov/35078402/)

- Source Code - [Github](https://github.com/bcgsc/AMPlify)

- Authors :  Chenkai Li, Darcy Sutherland, S Austin Hammond, Chen Yang, Figali Taho, Lauren Bergman, Simon Houston, René L Warren, Titus Wong, Linda M N Hoang, Caroline E Cameron, Caren C Helbing, Inanc Birol

- Date Published - 25 January, 2022               





### My interpretation of the model : 
- **Their objective** is to use a deep learning model (AMPlify) to predict effective peptides against a panel of WHO priority pathogens.

- **Why?** The concern it is working against is the same - ie the growing resistance to antibiotics and its globally degrading effectiveness. However, here the proposed solution is different. Unlike the second model, where the goal was to find similar compounds to antibiotics, this model sets out to find ALTERNATIVES to anitbiotics in novel antimicrobial peptides (AMPs) which are general purpose action drugs against bacteria, viruses, fungi and parasites. They use the predicted peptides against a list of WHO priority pathogens and 4 of the novel AMPs proved effective against multiple species of bacteria, including a multi-drug resistant isolate of e. coli.




### Relevance to Ersilia 

- The relevance to Ersilia is mostly retained from other models in that it is finding a novel solution to a potentially globally devastating problem that is slowly creeping towards us. Authorities and individuals researching this problem will only increase in the coming years and I believe Ersilia's fast and low-investment implementation of this and similar models will prove instrumental. This study also gets results effective against major diseases on the WHO priority pathogen list including e. coli, which is particularly puts rural and under developed areas at risk.

**Comment by joiboi08** [comment] 2023-10-31 08:04
Just updating that I have submitted the final application through Outreachy along with a timeline!

**Comment by GemmaTuron** [comment] 2023-11-03 14:51
Hello,

Thanks for your work during the Outreachy contribution period, we hope you enjoyed it! We will now close this issue while we work on the selection of interns. Thanks again!

**Closed by GemmaTuron** 2023-11-03 14:51 UTC
