### ISSUE TITLE
✍️ Contribution period: sohier Lotfy

### ISSUE THREAD

**Issue by soh-123** [ersilia-os/ersilia#988] opened 2024-03-05 15:32 UTC
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by soh-123** [comment] 2024-03-06 08:28
I'm thrilled to apply to the Ersilia project as an intern while contributing to an open source project is my main aim, I found the mission of the project appealing and Nobel to help data scientists by providing a scientific library of medicine and disease datasets will save so much time for them.

With a Bachelor's degree in Electronic Engineering and over three years of experience in product design and software engineering, I bring a unique blend of technical expertise and creative problem-solving skills to the table. Throughout my career, I have been passionate about leveraging technology to address societal challenges enhance user experiences, and drive positive outcomes. 

 am impressed by EOSI's commitment to diversity, inclusion, and creating a welcoming environment for all participants. As someone who values collaboration and mutual respect, I am excited about the opportunity to contribute to such a vibrant and inclusive community.

I am enthusiastic about the possibility of joining your team and contributing to the impactful work being done at EOSI. Thank you for considering my application. I look forward to the opportunity to discuss how I can contribute to your organization further.

**Comment by DhanshreeA** [comment] 2024-03-19 09:12
@soh-123 I do not see the link to your repository or any activity in the issue generally. Please let us know if you wish to continue, else we will close this issue. Thank you.

**Comment by soh-123** [comment] 2024-03-19 09:16
@DhanshreeA  I'm still working on the week 2 project. 

Apologies for not sharing my repo link, here it is:
[Week 2 repository](https://github.com/soh-123/Aqueous-solubility-prediction)

**Comment by GemmaTuron** [comment] 2024-03-21 08:43
Thansk @soh-123 we will provide feedback within the day today!

**Comment by DhanshreeA** [comment] 2024-03-22 08:15
Hi @soh-123 I see that the work for model reproducibility is incomplete and you have an error in your note book that has not been resolved. 

It looks like a KeyError, ie there is no column in your csv that is called 'solubility'. I also see that you are using an absolute system path for this csv in your notebook, and not one of the data files saved in the data folder. 
```python
csv_file_path = '/Users/sohierelsafty/workspace/Aqueous solubility prediction/Aqueous-solubility-prediction/data/reference_library.csv'
prediction_df = pd.read_csv(csv_file_path)
```

Please try to correct this issue.

**Comment by GemmaTuron** [comment] 2024-03-22 10:30
Good spot @DhanshreeA !

I suggest @soh-123  you focus on fixing this and then proceed to preparing the final application.
Thanks!

**Comment by soh-123** [comment] 2024-03-23 06:52
thank you @DhanshreeA @GemmaTuron

**Comment by soh-123** [comment] 2024-03-23 18:37
@DhanshreeA  I fixed the issue, please check

**Comment by DhanshreeA** [comment] 2024-03-25 11:34
Hi @soh-123 please proceed to submitting the final application.

**Closed as completed** 2024-04-02 17:21 UTC
